app/main/models.py
from flask_login import UserMixin
from app.thermocontrol.models import WebTempControl
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128));
    wtcs = db.relationship('WebTempControl', backref='owner', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from app.main.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
from app import db

from app.main import bp
from app.main.forms import LoginForm, RegistrationForm
from app.main.models import User

from app.thermocontrol.models import  WebTempControl, wtcs_schema
from app.cameracontrol.models import Camera

from flask import render_template, flash, redirect, url_for, session

from flask_login import current_user, login_user, logout_user
import json

@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
def index():
    '''
    The main function for rendering the principal site.
    '''
    if current_user.is_authenticated:
        wtcontrols = WebTempControl.query.filter_by(user_id = current_user.id).all();
        n_wtcs = WebTempControl.query.filter_by(user_id = current_user.id).count();
    else:
        wtcontrols = WebTempControl.query.all();
        n_wtcs = WebTempControl.query.count();


    cams = Camera.query.all();
    n_cameras = len(cams);

    wtc_json = json.dumps(wtcs_schema.dump(wtcontrols));
    return render_template('index.html', n_wtcs = n_wtcs, wtempcontrols = wtcontrols,
        wtc_json = wtc_json, n_cameras = n_cameras, cameras = cams);

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('main.index'))
    return render_template('login.html', title='Sign In', form=form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

app/main/templates/base.html
<!doctype html>
<html>
<head>

  <!--  CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css" />

  <!--  javascript -->
  <script src="https://unpkg.com/vue@latest/dist/vue.min.js"></script>
  <script src="https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <!-- Bootstrap Plugin -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js" integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P" crossorigin="anonymous"></script>

  <title>Device control server</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Device Control</a>
      <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
              <li class="nav-item">
                {% if current_user.is_anonymous %}
                  <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                {% else %}
                  <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                {% endif %}
              </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a class="nav-link" target="_blank" href="https://github.com/synqs/DeviceControlServer/issues/">Report Issue</a></li>
          <li><a class="nav-link" target="_blank" href="https://github.com/synqs/DeviceControlServer/">Source code</a></li>
    </ul>
    </div>
</nav>

<div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul>
            {% for category, message in messages %}
            {% if category == 'error' %}
              <div class="alert alert-warning alert-dismissible" role="alert">{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% else %}
              <div class="alert alert-info alert-dismissible" role="alert">{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endif %}

            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}
</div>
{% block scripts %}
{% endblock %}
</body>

app/main/templates/index.html
{% extends "base.html" %}
{% block app_content %}

{% if n_wtcs %}
<h1> WebTemp controls </h1>
{% if current_user.is_anonymous %}
 There are {{ n_wtcs }} web temperature controls installed. For more information you need to <a href="{{ url_for('main.login') }}">login</a>
{% else %}
<div class="container" id="wtcTable">
<wtc-table></wtc-table>
</div>
{% endif %}
{% endif %}

{% if n_cameras %}
<h1> Cameras</h1>
<table class="table table-hover" id ="arduino overview">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Folder</th>
    <th scope="col">Status</th>
    <th scope="col">Current Value</th>
    <th scope="col">Other actions </th>
  </tr>
  </thead>
  <tbody>
    {% for ard in cameras %}
    <tr>
      <td>{{ ard.id }}</td>
      <td>{{ ard.name }}</td>
      <td>{{ ard.folder }}</td>
      {% if ard.is_open() %}
      <td class="bg-success">Open</td>
      {% else %}
      <td class="bg-warning">Closed</td>
      {% endif %}
      <td id ='{{ ard.label() }}'>No value yet.</td>
      <td>
        <a class='btn btn-default' target="_blank" href="{{url_for('cameracontrol.change_camera', ard_nr = ard.id)}}">Settings</a>
        {% if ard.is_open() %}
        <a class='btn btn-default' target="_blank" href="{{url_for('cameracontrol.camera_details', ard_nr = ard.id)}}">Log</a>
        {% else %}
        <a class='btn btn-default' href="{{url_for('cameracontrol.start_camera', ard_nr = ard.id)}}">Start</a>
        {% endif %}
      <td>
    </tr>
    {% endfor %}
 </tbody>
</table>
{% endif %}

<div id="ping-pong-test">
  <ping-pong-widget/>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}

app/main/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('main.register') }}">Click to Register!</a></p>
{% endblock %}

{% block scripts %}
{{super()}}

{% endblock %}

app/main/templates/register.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

{% block scripts %}
{{super()}}

{% endblock %}